---
- block:
    - name: Add OpenPrinting APT Key
      apt_key:
        id: "{{cups_openprinting_apt_key_id}}"
        keyserver: "{{cups_openprinting_key_server}}"

    - name: Add OpenPrinting Package repo
      apt_repository:
        repo: "{{cups_openprinting_repo}}"
        state: present
        update_cache: yes
  when: cups_openprinting_apt_required is defined and cups_openprinting_apt_required == True

- name: Update apt cache.
  apt:
    update_cache: yes
    # upgrade: safe

# If the output is none or the command failed to find "install ok installed" then it means the package wasn't installed beforehand
- name: Check and register if expect related packages are already installed.
  command: dpkg -s {{item}} | grep 'install ok installed'
  register: apt_cups_expect_pkgs_already_installed
  with_items:
    - "{{ apt_cups_pre_install_packages }}"
  changed_when: False
  failed_when: False

- name: Ensure expect related packages are installed to guide us through CUPS installation.
  apt: name={{ item }} state=present
  with_items:
    - "{{ apt_cups_pre_install_packages }}"
...