---
- name: Apt Packages Install CUPS
  include: apt_cups_install.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Yum Packages Install CUPS
  include: yum_cups_install.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Adds lpadmin group
  group:
    name: lpadmin
    state: present

- name: Add accounts to lpadmin group (CUPS admin)
  user:
    name: "{{item}}"
    append: yes
    groups: "{{cups_admin_grp}}"
  with_items: 
    - "{{cups_lpadmin_users}}"

- name: Include - CUPS-LPD
  include: cups_install_lpd.yml
  when: 
    - (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
    - cups_lpd
...