---
- name: Creating CUPS tmp location {{ cups_tmp_location }}
  file:
    path: "{{cups_tmp_location}}"
    recurse: yes
    state: directory

- name: Creating {{ cups_ppd_shared_location }}
  file:
    path: "{{cups_ppd_shared_location}}"
    recurse: yes
    state: directory
    
- name: Apt Packages
  include: apt_pre_install_packages.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Yum Packages
  include: yum_pre_install_packages.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
...