---
- name: Creating CUPS tmp location {{ cups_tmp_location }}
  file:
    path: "{{ cups_tmp_location }}"
    recurse: yes
    state: directory

- name: Creating {{ cups_ppd_shared_location }}
  file:
    path: "{{ cups_ppd_shared_location }}"
    recurse: yes
    state: directory

- block:
    - name: install lsb
      yum:
        name: lsb
        state: present

    - name: Add Openprinting Repo
      yum_repository:
        name: openprinting
        description: OpenPrinting LSB-based driver packages
        baseurl: "{{ cups_openprinting_rpm_repo }}"
        gpgcheck: no
  when: cups_openprinting_required is defined and cups_openprinting_required

- name: Ensure expect related packages are installed to guide us through CUPS installation.
  yum: 
    name: "{{ item }}"
    state: present
  register: cups_expect_install
  with_items:
    - "{{ cups_expect_packages }}"
